### ISSUE TITLE
Corrections to final project for use as sample

### ISSUE THREAD

**Issue by rpseely** [ecn310/course-project-nepobabies#18]
### Tracking Corrections to Final Project

As instructed by Professor Buzard, I will be making some edits to the final report write-up and the do-file for potential use as a sample project in future sections of ECN 310. I will be using the critique from the [grading rubric](https://github.com/ecn310/course-project-nepobabies/blob/main/Course%20Project%20Rubric--NepoBabies.pdf) used by Prof. Buzard to guide my editing of the project.

**Comment by kbuzard** [comment]
@rpseely I just read over the report, and it looks great! Please go ahead and finalize it.

I'm going through the reproducibility package now. I'll keep digging, but I wanted to let you know that the link in the readme in the Final Report folder has a broken link: the one to the reproducibility package doesn't work. That doesn't affect any of the links in the Data Appendix, so you can finalize that and then fix this link.

**Comment by kbuzard** [comment]
@rpseely NEVERMIND. The link to the .do file in the Data Appendix gets a "file not found" message, as does the link to the .log file.

It would also be good to make the data appendix and actual appendix section so it shows up in the table of contents. It's super simple. See [this](https://texfaq.org/FAQ-appendix) explainer.

Then, please drop a reference to the data appendix into the data section somewhere (it could be in a footnote if that makes the most sense). You can hyperlink to the section by doing something like the following with the data appendix setup:
```
\appendix
\section{How I became inspired}
\label{sec:appendix}
```
And then use the reference in a sentence, like "The \ref{sec:appendix} provides details of the data acquisition, manipulation and analysis." (or it might have to be some variation on this depending on how things are set up--the \ref statement may print out the section number instead of the name "Data Appendix." Bottom line: the \ref command will insert a hyperlink, and you can manipulate what it looks like, for instance, with the nameref package (see first answer [here](https://tex.stackexchange.com/questions/66896/ref-chapter-name-in-latex)).

**Comment by rpseely** [comment]
## Tuesday, June 11, 2024

### Fixes
-  I fixed all the links in the README (minus the final draft link), reproducibility package, and appendix.

### Appendix and Sections
- I added the code from the website you suggested above and I set up a hyperlink in the data section so that it can be accessed from there.
- At first I tried playing around with a different option that also included the references section as one of the numbered sections, but it kept producing a numbered section header and then another un-numbered section section header right below it and I could not resolve that issue (I presume it has something to do with reading in the .bib file with the \bibliographystyle{apalike} command).

@kbuzard I attached a file below so you can see what it looks like. The only thing I am not 100% about is how the references section is different from the appendix and the rest of the sections. 
[NepoBabies.6.12.24.pdf](https://github.com/user-attachments/files/15798313/NepoBabies.6.12.24.pdf)

**Comment by kbuzard** [comment]
@rpseely I think the section stuff looks fine for both the references and the appendix! Don't worry about pushing it any further. There's probably a way to make it work the way you were trying (which I agree would be great), but I see this all the time in papers and people are used to looking for the references in the right place so not a big deal.

All the links in the data appendix work! I don't think it needs any further revisions.

For the OneDrive issue, the most elegant way around it would be to provide information about where the data is downloaded from on the GSS website. Then someone could download that big file themselves.
- Then, have GSSclean_noRDs.dta in your Data folder on OneDrive, and everything can flow from there.

For the purposes of putting this on my website, I think it's good to go as soon as you upload the .tex and .pdf and make sure that the right version is linked on the main readme.

Two more things I suggest:
- Clean up the branches on your repo. When I click on the final report on the main readme, I think it's taking me to a different branch b/c the files aren't organized.
- Add the location of the report at the bottom of the reproducibility readme (with a note that it was written on Overleaf but that the final .tex file is available on your repo as well).

**Comment by rpseely** [comment]
@kbuzard I added a comment in the appendix on accessing the original GSS dataset on their website and added a hyperlink. I uploaded the .pdf and .tex for the final report and they are in the [final report](https://github.com/ecn310/course-project-nepobabies/tree/main/Final%20Report) folder on this repo.

**Comment by rpseely** [comment]
## Wednesday, June 19, 2024
I have been looking for the gss7222_r1 release with little success. On my first keyword search on google, there was only website match that came up, which was the link to the Nepobabies project on Prof. Buzard's website, so that was funny. I submitted a contact form on the GSS website asking for a link to the original data release that we used. I tried uploading the file directly to GitHub but as we discussed it was too big.

@kbuzard I went on your website and noticed that the hyperlink to the accidents project leads to the PDF of the nepobabies project.

**Comment by kbuzard** [comment]
@rpseely Another option: you could try downloading the version that is currently on their website and see if you get the same results. You could even start off by using something like [this](https://www.stata.com/manuals/dcf.pdf) to compare the two datasets. If your results are the same, then you can just link to the current version of the dataset.

**Comment by rpseely** [comment]
> @rpseely Another option: you could try downloading the version that is currently on their website and see if you get the same results. You could even start off by using something like [this](https://www.stata.com/manuals/dcf.pdf) to compare the two datasets. If your results are the same, then you can just link to the current version of the dataset.

@kbuzard Unfortunately I am not able to open the r1 or r3 versions of the GSS data in Stata on the RDS because the files are too big. I tried opening them in R but it stopped responding (this happened just now and when I tried it last week).

**Comment by kbuzard** [comment]
> Unfortunately I am not able to open the r1 or r3 versions of the GSS data in Stata on the RDS because the files are too big. I tried opening them in R but it stopped responding (this happened just now and when I tried it last week).

I just emailed the research computing people in Maxwell about this. I'm sure they'll have a solution. I'm going to be in the car for the rest of the afternoon so won't be able to respond to them. So, if they ask a question that you can answer, please go ahead and reply.

**Comment by rpseely** [comment]
@kbuzard I have phenomenal Nepobabies news! The results from the gss7222_r3 are the exact same as those from the gss7222_r1! Once I learned about unzipping folders/files, I was able to get the r3 results. I then made these edits on overleaf and I have attached a PDF here. If you like the changes in the appendix, I will go ahead and update the final report links on the GitHub repo.

**Comment by kbuzard** [comment]
> @kbuzard I have phenomenal Nepobabies news! The results from the gss7222_r3 are the exact same as those from the gss7222_r1! Once I learned about unzipping folders/files, I was able to get the r3 results. I then made these edits on overleaf and I have attached a PDF here. If you like the changes in the appendix, I will go ahead and update the final report links on the GitHub repo. [NepoBabies.6.25.24.pdf](https://github.com/user-attachments/files/15974683/NepoBabies.6.25.24.pdf)

@rpseely The updated PDF looks good! Will you also adjust the first item in Final Report/ReproducibilityPackage.md to reflect the data coming from the GSS website?

**Comment by ryanpseely** [comment]
> @rpseely The updated PDF looks good! Will you also adjust the first item in Final Report/ReproducibilityPackage.md to reflect the data coming from the GSS website?

@kbuzard I have updated all the reproducibility package, the file organization with the updated PDF and TEX files, and all of the links.

**Comment by kbuzard** [comment]
Great job! I'm sending it to Professor Zhu now!
